Music_App/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :users, only: [:create, :new, :show, :index]
  resource :session, only: [:new, :create, :destroy]
end

Music_App/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

Music_App/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord  #FIGVAPER
    validates :email, :session_token, presence: true, uniqueness: true
    validates :password_digest, presence: true
    validates :password, length: { minimum: 6 }, allow_nil: true
    before_validation :ensure_session_token
    attr_reader :password

    def self.find_by_credentials(email, password) #F
        user = User.find_by(email: email)
        user&.is_password?(password) ? user : nil 
    end
    
    def generate_unique_session_token #G
        loop do
            session_token = SecureRandom::urlsafe_base64(16)
            return session_token unless User.exists?(session_token: session_token)
        end
    end

    def reset_session_token! #R
        self.session_token = generate_unique_session_token
        self.save! 
        self.session_token
    end

    def ensure_session_token #E
        self.session_token ||= generate_unique_session_token
    end

    def password=(password) #P
        self.password_digest = BCrypt::Password.create(password)
        @password = password
    end

    def is_password?(password) #I
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end
end

Music_App/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?
    protect_from_forgery with: :null_session

    def current_user
        return nil unless session[:session_token]
        @current_user = User.find_by(session_token: session[:session_token])
    end

    def logged_in?
        !!@current_user
    end

    def login!(user)
        @current_user = user 
        session[:session_token] = user.reset_session_token!
    end

    def logout!
        @current_user.reset_session_token if logged_in?
        session[:session_token] = nil 
        @current_user = nil 
    end
end

Music_App/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def create
        @user = User.find_by_credentials(
            params[:user][:email],
            params[:user][:password]
        )
        if @user.nil?
            flash.now[:errors] = ["Incorrect email and/or password"]
            render :new 
        else
            login!(@user)
            redirect_to user_url(@user)
        end
    end

    def new
        render :new #login page
    end

    def destroy
        logout!
        redirect_to new_session_url
    end


end

Music_App/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @users = User.all
        render json :@users
    end
    
    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.new(user_params)
        if @user.save!
            login!(@user)
            flash[:messages] = ["Successfully Created"]
            redirect_to user_url(@user)
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def show
        @user = User.find(params[:id])
        render :show
    end

    private
    def user_params
        params.require(:user).permit(:email, :password)
    end
end

Music_App/app/helpers/application_helper.rb
module ApplicationHelper

    def auth_token
        "<input
        type='hidden'
        name='authenticity_token
        value='#{form_authenticity_token}'>".html_safe
    end
end

Music_App/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

    <header>
        <h1>MusicApp</h1>
    </header>

  <body>
    <nav>
      <ul class="nav-list">
        <% if logged_in? %>
            <li><a href="<%= new_session_url %>"> Sign out </a></li>
        <% else %>
            <li><a href="<%= new_session_url %>"> Login </a></li>
            <li><a href="<%= new_user_url %>"> Sign up </a></li>
        <% end %>
      </ul>
    </nav>

    <%= yield %>
  </body>
</html>

Music_App/app/views/users/new.html.erb
<h1> Sign Up Here </h1>

<form action="<%= users_url %>" method="POST"> 
<%= auth_token %>

    <label>
    Email:
    </label>
    <input name="user[email]" type="text" value="<%= @user.email %>"> 

    <br>

    <label>
    Password:
    </label>
    <input name="user[password]" type="password" value=""> 

    <br>

<input type="submit" value="Create Account"> 
</form>

Music_App/app/views/users/show.html.erb
<h1>Here's your account information</h1>

<ul>
    <li>Email: <%= @user.email %></li>
</ul>